version: '3'

services:
  postgresdb:
    container_name: postgres-database
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    networks:
      - spring-app
    restart: always

  spring-boot-docker:
    container_name: spring-app
    image: spring-boot-docker:0.0.1-SNAPSHOT
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgresdb
    networks:
      - spring-app
    restart: always
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M

networks:
  spring-app:
    driver: bridge
