version: '3'

services:
  postgresdb:
    container_name: postgres-database
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    networks:
      - spring-app
    restart: always


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "America/Sao_Paulo"
    ports:
      - "16543:80"
    depends_on:
      - postgresdb
    networks:
      - spring-app
    restart: always





networks:
  spring-app:
    driver: bridge